package com.revature.daos;

import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;

import com.google.common.hash.Hashing;
import com.revature.beans.User;
import com.revature.utils.ConnectionUtil;

public class SignupDao {

	/**
	 * method to return random salt
	 * @return salt string
	 */
	private String getSaltString() {
        String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < 18) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;

    }
	/**
	 * func to hash a password with salt
	 * @param password password being hashed
	 * @param salt salt string
	 * @return sha256 of pass+hash
	 */
	private String hash(String password,String salt)
	{
		String sha256hex = Hashing.sha256()
				  .hashString(password+salt, StandardCharsets.UTF_8)
				  .toString();
		return sha256hex;
	}
	/**
	 * func to save a user
	 * @param u user to save used only through postman
	 * @return
	 */
	public boolean saveUser(User u)
	{
		try (Connection conn = ConnectionUtil.getConnection()) {
			String sql = "insert into ERS_USERS (ERS_USERNAME,ERS_PASSWORD,salt,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_ROLE_ID) VALUES (?,?,?,?,?,?,?) RETURNING ERS_USERS_ID";
			PreparedStatement ps = conn.prepareStatement(sql);
			ps.setString(1, u.getUsername());
			String salt = getSaltString();
			ps.setString(2, hash(u.getPassword(), salt));
			ps.setString(3, salt);
			ps.setString(4, u.getFirstname());
			ps.setString(5, u.getLastname());
			ps.setString(6, u.getEmail());
			ps.setInt(7, u.getRole());
			ResultSet rs = ps.executeQuery();
			if(rs.next())
			{
				int id = rs.getInt("ERS_USERS_ID");
				u.setId(id);
			}
			return true;
		} catch (SQLException e) {
			//TODO autogenerated
			e.printStackTrace();
			return false;
		}
	}
}
